name: Lint JSON Schema with jv

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install linter
      run: |
        curl -sL https://github.com/santhosh-tekuri/jsonschema/releases/download/v6.0.1/jv-v6.0.1-linux-amd64.tar.gz > jv.tar.gz
        mkdir -p $HOME/.local/bin
        tar zxf jv.tar.gz -C $HOME/.local/bin
        echo $HOME/.local/bin >> $GITHUB_PATH

    - name: Run JSON Schema lint
      run: |
        jv corporation/schema.json corporation/*/*.json
